name: Gail Armstrong
favicon: null
layout_spectrum: 0.10615229280665517
typography_spectrum: 0.5218638351652771
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8053540578112006
  lightness: 0.18960587680339813
  saturation: 0.8897478259168565
  rhythmicContrast: 0.27170258457772434
purpose: []
